package Job.Portal.System.model;

import jakarta.persistence.*;

import java.time.LocalDate;

/**
 * Entity class representing an academic degree.
 * This class maps to a table in the database where degree details are stored.
 */
@Entity
public class Degree {

    /**
     * The primary key for the Degree entity.
     * This ID is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;  // Unique identifier for the degree

    /**
     * The name of the degree (e.g., BSc, MSc).
     */
    private String degree;  // Name of the degree

    /**
     * The name of the school or university where the degree was obtained.
     */
    private String school;  // Institution that awarded the degree

    /**
     * The graduation date when the degree was completed.
     */
    private LocalDate gradDate;  // Date of graduation

    /**
     * The grade or GPA obtained for the degree.
     */
    private String grade;  // Grade or GPA achieved

    /**
     * Many-to-one relationship with the Resume entity.
     * This indicates that multiple degrees can be associated with a single resume.
     */
    @ManyToOne
    @JoinColumn(name = "resume_id")
    private Resume resume;  // The resume to which this degree is associated
}
