package Job.Portal.System.model;

import jakarta.persistence.*;

/**
 * Entity class representing a link associated with a resume.
 * This class maps to a table in the database where links are stored.
 */
@Entity
public class Links {

    /**
     * The primary key for the Links entity.
     * This ID is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;  // Unique identifier for the link

    /**
     * A label or description for the link (e.g., "Portfolio", "LinkedIn").
     */
    private String label;  // Description or label for the link

    /**
     * The URL of the link.
     */
    private String url;  // The actual URL that the link points to

    /**
     * Many-to-one relationship with the Resume entity.
     * This indicates that multiple links can be associated with a single resume.
     */
    @ManyToOne
    @JoinColumn(name = "resume_id")
    private Resume resume;  // The resume to which this link is associated
}
