package Job.Portal.System.model;

import jakarta.persistence.*;
import java.time.LocalDate;

/**
 * Entity class representing a project associated with a resume.
 * This class maps to a table in the database where projects are stored.
 */
@Entity
public class Projects {

    /**
     * The primary key for the Projects entity.
     * This ID is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;  // Unique identifier for the project

    /**
     * The title or name of the project.
     */
    private String title;  // Title of the project

    /**
     * A detailed description of the project.
     * This field uses a large object type (Lob) to handle potentially long text.
     */
    @Lob
    private String description;  // Description of the project

    /**
     * The duration of the project in months or years.
     * This is an integer value representing the length of the project.
     */
    private Integer duration;  // Duration of the project

    /**
     * The end date of the project.
     * This date represents when the project was completed.
     */
    private LocalDate endDate;  // End date of the project

    /**
     * Many-to-one relationship with the Resume entity.
     * This indicates that multiple projects can be associated with a single resume.
     */
    @ManyToOne
    @JoinColumn(name = "resume_id")
    private Resume resume;  // The resume to which this project is associated
}
