package Job.Portal.System.model;

import jakarta.persistence.*;

/**
 * Entity class representing a reference associated with a resume.
 * This class maps to a table in the database where references are stored.
 */
@Entity
public class References {

    /**
     * The primary key for the References entity.
     * This ID is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;  // Unique identifier for the reference

    /**
     * The full name of the reference.
     */
    private String fullName;  // Full name of the reference

    /**
     * The organization where the reference is employed.
     */
    private String organization;  // Organization of the reference

    /**
     * The phone number of the reference.
     */
    private String phone;  // Phone number of the reference

    /**
     * The email address of the reference.
     */
    private String email;  // Email address of the reference

    /**
     * Many-to-one relationship with the Resume entity.
     * This indicates that multiple references can be associated with a single resume.
     */
    @ManyToOne
    @JoinColumn(name = "resume_id")
    private Resume resume;  // The resume to which this reference is associated
}
