package Job.Portal.System.model;

import jakarta.persistence.*;

/**
 * Entity class representing a skill associated with a resume.
 * This class maps to a table in the database where skills are stored.
 */
@Entity
public class Skills {

    /**
     * The primary key for the Skills entity.
     * This ID is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;  // Unique identifier for the skill

    /**
     * The name of the skill.
     */
    private String name;  // Name of the skill (e.g., "Java", "Project Management")

    /**
     * The number of years of experience with the skill.
     */
    private Integer years;  // Number of years of experience with the skill

    /**
     * Many-to-one relationship with the Resume entity.
     * This indicates that multiple skills can be associated with a single resume.
     */
    @ManyToOne
    @JoinColumn(name = "resume_id")
    private Resume resume;  // The resume to which this skill is associated

    // Getters and setters
    // These methods are automatically generated by Lombok or manually created for accessing and modifying the fields
}
